version: '3.8'

services:
  php:
    container_name: php_person
    build:
      dockerfile: .docker/php/Dockerfile
    ports:
      - '9002:9001'
    volumes:
      - .:/var/www/app
  nginx:
    container_name: nginx_person
    image: nginx:stable-alpine
    ports:
      - '9092:80'
    volumes:
      - .:/var/www/app
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
  database:
    container_name: database_person
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: database_person
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - '${DATABASE_PORT:-4306}:3306'
    volumes:
      - ./.docker/database:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '${PHPMYADMIN_PORT:-9898}:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database_person
    depends_on:
      - database
###> doctrine/doctrine-bundle ###
#   database:
#     image: postgres:${POSTGRES_VERSION:-15}-alpine
#     environment:
#       POSTGRES_DB: ${POSTGRES_DB:-app}
#       # You should definitely change the password in production
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
#       POSTGRES_USER: ${POSTGRES_USER:-app}
#     volumes:
#       - database_data:/var/lib/postgresql/data:rw
#       # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#       # - ./docker/db/data:/var/lib/postgresql/data:rw
# ###< doctrine/doctrine-bundle ###

# volumes:
# ###> doctrine/doctrine-bundle ###
#   database_data:
# ###< doctrine/doctrine-bundle ###
